/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  BalanceOfUtil2,
  BalanceOfUtil2Interface,
} from "../BalanceOfUtil2";

const _abi = [
  {
    type: "function",
    stateMutability: "view",
    outputs: [
      {
        type: "uint256",
        name: "",
        internalType: "uint256",
      },
    ],
    name: "getNativeBalance",
    inputs: [
      {
        type: "address",
        name: "userAddress",
        internalType: "address",
      },
    ],
  },
] as const;

export class BalanceOfUtil2__factory {
  static readonly abi = _abi;
  static createInterface(): BalanceOfUtil2Interface {
    return new Interface(_abi) as BalanceOfUtil2Interface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): BalanceOfUtil2 {
    return new Contract(address, _abi, runner) as unknown as BalanceOfUtil2;
  }
}
