/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type { ERC1967Proxy, ERC1967ProxyInterface } from "../ERC1967Proxy";

const _abi = [
  {
    type: "constructor",
    stateMutability: "payable",
    inputs: [
      {
        type: "address",
        name: "_logic",
        internalType: "address",
      },
      {
        type: "bytes",
        name: "_data",
        internalType: "bytes",
      },
    ],
  },
  {
    type: "event",
    name: "AdminChanged",
    inputs: [
      {
        type: "address",
        name: "previousAdmin",
        internalType: "address",
        indexed: false,
      },
      {
        type: "address",
        name: "newAdmin",
        internalType: "address",
        indexed: false,
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "BeaconUpgraded",
    inputs: [
      {
        type: "address",
        name: "beacon",
        internalType: "address",
        indexed: true,
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "Upgraded",
    inputs: [
      {
        type: "address",
        name: "implementation",
        internalType: "address",
        indexed: true,
      },
    ],
    anonymous: false,
  },
  {
    type: "fallback",
    stateMutability: "payable",
  },
  {
    type: "receive",
    stateMutability: "payable",
  },
] as const;

export class ERC1967Proxy__factory {
  static readonly abi = _abi;
  static createInterface(): ERC1967ProxyInterface {
    return new Interface(_abi) as ERC1967ProxyInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): ERC1967Proxy {
    return new Contract(address, _abi, runner) as unknown as ERC1967Proxy;
  }
}
